name    'lex-approx'
version '1.0.0'
dependency 'puppetlabs/concat', '>= 1.0.0'
source 'git://github.com/rlex/puppet-approx.git'
author 'Lex Rivera <me@lex.io>'
license 'Creative Commons Attribution 3.0 Unported License'
summary 'Puppet approx management module'
description 'A module to deploy and manage approx (APT mirror proxy)'
project_page 'https://github.com/rlex/puppet-approx'
